require<string>('file-loader?name=[name].[ext]!./index.html')
require<string>('file-loader?name=style.css!sass-loader!./style.scss')
require<string>('file-loader?name=robots.txt!../static/robots.txt')
require<string>('file-loader?name=marx.min.css!../node_modules/marx-css/css/marx.min.css')
require<string>('file-loader?name=marx.min.css.map!../node_modules/marx-css/css/marx.min.css.map')
